### ISSUE TITLE
ansible密钥分发

### ISSUE THREAD

**Issue by zhaobei** [zhaobei/ansible-playbook#1]
# ansible密钥分发

首先编辑主机组

```
vim /etc/ansible/hosts
```

`ip ansible_user=root ansible_ssh_pass="pwd"`
修改配置文件

```
# vi /etc/ansible/ansible.cfg

host_key_checking = False
```

`host_key_checking = False`

编辑 ansible_ssh.yaml

```
---
- hosts: backup
  user: root
  tasks:
   - name: ssh_copy
     authorized_key: user=root key="{{ lookup('file','/root/.ssh/id_rsa.pub') }}"
     tags:
       - sshkey
```
